lr: 1e-3
use_ema: true
horizon: 10

batch_size: 64
subseq_len: 20
stride: 1

state_dim: 4
latent_dim: 8
control_dim: 1
forcing_dim: 0

beta_kl: 0.01

state_cols: ['$T_1$', '$T_2$', '$T_{wall}$', '$T_{out}$']
control_cols: ['u_0']
forcing_cols: []
scale: true
val_ratio: 0.2
split_mode: 'random'