# --- Experiment Metadata ---
exp_name: "koopman_exp"
checkpoint_dir: "./checkpoints"

# --- Model Architecture ---
dims:
  state_dim: 3
  latent_dim: 32
  control_dim: 0
  forcing_dim: 0
  hidden_dim: 64
  hidden_depth: 8

# --- Data Pipeline ---
data:
  dataset: "csv/lorenz_dt_0.1_few"
  subseq_len: 80
  stride: 1
  cyclic_features: [] #
  state_cols: ['$x$', '$y$', '$z$']
  control_cols: []
  forcing_cols: []
  scale: true
  val_ratio: 0.2
  split_mode: 'window'
  time_col: 'time'


# --- Training & Optimization ---
train:
  encoder_type: resmlp
  decoder_type: resmlp     # or "linear"
  operator_type: learnable_complex_diag
  use_forcing: true
  forcing_net: linear
  lr: 5e-4
  batch_size: 128
  backend: 'torch'
  use_ema: false
  ema_decay: 1
  val_interval: 100
  save_interval: 100
  min_entropy_threshold: 1.0
  device: 'cuda'
  horizon: 45
  plot_forcing_mode: "dimensions"
  stochastic: False
  encode_control: False
  concat_true: False

# --- Physics & Loss Weights (The Coefficients) ---
weights:
  gamma_1: 10.0        # Koopman Consistency: ||z_pred - z_enc||
  gamma_2: 10.0        # State Reconstruction: ||x_pred - x_true||
  rollout_decay: 0.9
  epsilon_1: 10.0      # Encoder Decoder Reconstruction init
  epsilon_2: 10.0     # Encoder Decoder Reconstruction all
  beta_kl: 0.0     # KL Divergence: Latent regularization
  alpha_ent: 0.1      # Entropy: Prevents latent collapse
  lambda_vamp: 0.0    # VAMP-2: Maximizes kinetic variance
  delta_spec: 0.0  # Spectral Penalty: Stability (eigs <= 1)
  zero_gain: 0.0      # Zero-State: Physical origin mapping
  epsilon_3: 0.0      # Control Reconstruction
  lambda_forcing: 0.1 # Forcing Regularization (HAVOK v_r)